/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at

        http://aws.amazon.com/apache2.0/

    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
"plain bagel": "the exchange for plain bagel is 1.5 grams with no modifier.",
"bagel": "the exchange for bagel is  grams with no modifier.",
"corn bread": "the exchange for corn bread is 1.8 grams with no modifier.",
"croissant": "the exchange for croissant is 1.8 grams with no modifier.",
"dinner role": "the exchange for dinner role is 1.7 grams with no modifier.",
"english muffin": "the exchange for english muffin is 1.7 grams with no modifier.",
"flour tortilla": "the exchange for flour tortilla is 1.6 grams with no modifier.",
"tortilla": "the exchange for tortilla is  grams with no modifier.",
"french bread": "the exchange for french bread is 1.5 grams with no modifier.",
"low calorie white bread": "the exchange for low calorie white bread is 1.9 grams with no modifier.",
"pita": "the exchange for pita is 1.5 grams with no modifier.",
"pita bread": "the exchange for pita bread is  grams with no modifier.",
"potato bread": "the exchange for potato bread is 1.7 grams with no modifier.",
"pumpernickel": "the exchange for pumpernickel is 1.9 grams with no modifier.",
"pumpernickel bread": "the exchange for pumpernickel bread is  grams with no modifier.",
"rye": "the exchange for rye is 1.8 grams with no modifier.",
"rye bread": "the exchange for rye bread is  grams with no modifier.",
"wheat bread": "the exchange for wheat bread is 2 grams with no modifier.",
"white bread": "the exchange for white bread is 1.7 grams with no modifier.",
"nor beef broth": "the exchange for nor beef broth is 32.2 grams with no modifier.",
"beef broth": "the exchange for beef broth is  grams with no modifier.",
"nor chicken broth": "the exchange for nor chicken broth is 75.3 grams with no modifier.",
"chicken broth": "the exchange for chicken broth is  grams with no modifier.",
"nor vegetable broth": "the exchange for nor vegetable broth is 45.2 grams with no modifier.",
"vegetable broth": "the exchange for vegetable broth is  grams with no modifier.",
"chicken bouillion": "the exchange for chicken bouillion is 4 grams with no modifier.",
"beef bouillion": "the exchange for beef bouillion is  grams with no modifier.",
"swanson beef broth": "the exchange for swanson beef broth is 75.3 grams with no modifier.",
"swanson chicken broth": "the exchange for swanson chicken broth is 113 grams with no modifier.",
"swanson vegetable broth": "the exchange for swanson vegetable broth is 75.3 grams with no modifier.",
"bran falkes": "the exchange for bran falkes is 1.1 grams with no modifier.",
"cheerio": "the exchange for cheerio is 1.1 grams with no modifier.",
"cocoa puffs": "the exchange for cocoa puffs is 1.1 grams with no modifier.",
"corn flakes": "the exchange for corn flakes is 1 grams with no modifier.",
"corn grits": "the exchange for corn grits is 1.1 grams with no modifier.",
"corn pops": "the exchange for corn pops is 1.1 grams with no modifier.",
"cream of wheat": "the exchange for cream of wheat is 1.1 grams with no modifier.",
"farina": "the exchange for farina is 1.1 grams with no modifier.",
"grape nuts": "the exchange for grape nuts is 1.1 grams with no modifier.",
"honey nut cheerio": "the exchange for honey nut cheerio is 1.1 grams with no modifier.",
"berry berry kix": "the exchange for berry berry kix is 1.1 grams with no modifier.",
"kix": "the exchange for kix is 1 grams with no modifier.",
"kix cereal": "the exchange for kix cereal is  grams with no modifier.",
"oatmeal": "the exchange for oatmeal is 1.2 grams with no modifier.",
"life cereal": "the exchange for life cereal is 1.1 grams with no modifier.",
"puffed rice": "the exchange for puffed rice is 1 grams with no modifier.",
"puffed wheat": "the exchange for puffed wheat is 1 grams with no modifier.",
"rice chex": "the exchange for rice chex is 1.1 grams with no modifier.",
"chex cereal": "the exchange for chex cereal is  grams with no modifier.",
"rice crispy": "the exchange for rice crispy is 1.1 grams with no modifier.",
"shredded wheat": "the exchange for shredded wheat is 1.1 grams with no modifier.",
"wheat germ": "the exchange for wheat germ is 1.2 grams with no modifier.",
"air crisp": "the exchange for air crisp is 1 grams with no modifier.",
"animal cracker": "the exchange for animal cracker is 1.2 grams with no modifier.",
"better cheddar": "the exchange for better cheddar is 1.5 grams with no modifier.",
"bread crumb": "the exchange for bread crumb is 1.2 grams with no modifier.",
"cheesenip": "the exchange for cheesenip is 1.5 grams with no modifier.",
"cheese it": "the exchange for cheese it is 1.5 grams with no modifier.",
"club cracker": "the exchange for club cracker is 1.4 grams with no modifier.",
"crisp bread": "the exchange for crisp bread is 1.1 grams with no modifier.",
"goldfish": "the exchange for goldfish is 1.3 grams with no modifier.",
"goldfish cracker": "the exchange for goldfish cracker is  grams with no modifier.",
"graham": "the exchange for graham is 1.2 grams with no modifier.",
"graham cracker": "the exchange for graham cracker is  grams with no modifier.",
"matzah": "the exchange for matzah is 1.2 grams with no modifier.",
"melba toast": "the exchange for melba toast is 1.1 grams with no modifier.",
"oyster cracker": "the exchange for oyster cracker is 1 grams with no modifier.",
"rice cake": "the exchange for rice cake is 1.1 grams with no modifier.",
"ritz cracker": "the exchange for ritz cracker is 1.4 grams with no modifier.",
"saltine": "the exchange for saltine is 1.3 grams with no modifier.",
"saltine cracker": "the exchange for saltine cracker is  grams with no modifier.",
"seasoned crouton": "the exchange for seasoned crouton is 1.3 grams with no modifier.",
"crouton": "the exchange for crouton is  grams with no modifier.",
"townhouse cracker": "the exchange for townhouse cracker is 1.5 grams with no modifier.",
"triscuit": "the exchange for triscuit is 1.3 grams with no modifier.",
"waverly": "the exchange for waverly is 1 grams with no modifier.",
"wheat cracker": "the exchange for wheat cracker is 1.4 grams with no modifier.",
"wheat thin": "the exchange for wheat thin is 1.4 grams with no modifier.",
"wheatables": "the exchange for wheatables is 1.4 grams with no modifier.",
"apple": "the exchange for apple is 7.1 grams with no modifier.",
"apple with skin": "the exchange for apple with skin is  grams with no modifier.",
"apple without skin": "the exchange for apple without skin is 7.7 grams with no modifier.",
"apple sauce": "the exchange for apple sauce is 5 grams with no modifier.",
"sweetened apple sauce": "the exchange for sweetened apple sauce is  grams with no modifier.",
"unsweetened apple sauce": "the exchange for unsweetened apple sauce is 8.7 grams with no modifier.",
"apricot in syrup": "the exchange for apricot in syrup is 5.9 grams with no modifier.",
"apricots in syrup": "the exchange for apricots in syrup is  grams with no modifier.",
"apricot in water": "the exchange for apricot in water is 14.1 grams with no modifier.",
"apricots in water": "the exchange for apricots in water is  grams with no modifier.",
"dried apricot": "the exchange for dried apricot is 1.5 grams with no modifier.",
"apricot": "the exchange for apricot is 8 grams with no modifier.",
"fresh apricot": "the exchange for fresh apricot is  grams with no modifier.",
"avocado": "the exchange for avocado is 9.5 grams with with a -1 gram modifier.",
"banana": "the exchange for banana is 4.2 grams with no modifier.",
"blackberry": "the exchange for blackberry is 9.1 grams with no modifier.",
"fresh blackberry": "the exchange for fresh blackberry is  grams with no modifier.",
"frozen blackberry": "the exchange for frozen blackberry is 6 grams with no modifier.",
"blueberry": "the exchange for blueberry is 6.5 grams with no modifier.",
"fresh blueberry": "the exchange for fresh blueberry is  grams with no modifier.",
"freeze dried blueberry": "the exchange for freeze dried blueberry is 1.1 grams with no modifier.",
"frozen blueberry": "the exchange for frozen blueberry is 8 grams with no modifier.",
"cantaloupe": "the exchange for cantaloupe is 11.1 grams with no modifier.",
"maraschino cherry": "the exchange for maraschino cherry is 2.3 grams with no modifier.",
"sour cherry": "the exchange for sour cherry is 7.6 grams with no modifier.",
"sweet cherry in water": "the exchange for sweet cherry in water is 8 grams with no modifier.",
"sweet cherries in water": "the exchange for sweet cherries in water is  grams with no modifier.",
"fresh cherry": "the exchange for fresh cherry is 5.9 grams with no modifier.",
"sweet cherry": "the exchange for sweet cherry is  grams with no modifier.",
"fresh cherries": "the exchange for fresh cherries is  grams with no modifier.",
"clementine": "the exchange for clementine is 7.8 grams with no modifier.",
"dried cranberry": "the exchange for dried cranberry is 1.2 grams with no modifier.",
"fresh cranberry": "the exchange for fresh cranberry is 7.9 grams with no modifier.",
"cranberry": "the exchange for cranberry is  grams with no modifier.",
"dried fig": "the exchange for dried fig is 1.5 grams with no modifier.",
"fig": "the exchange for fig is  grams with no modifier.",
"pink grapefruit": "the exchange for pink grapefruit is 8.8 grams with no modifier.",
"red grapefruit": "the exchange for red grapefruit is  grams with no modifier.",
"white grapefruit": "the exchange for white grapefruit is 11 grams with no modifier.",
"grape": "the exchange for grape is 5.5 grams with no modifier.",
"guava": "the exchange for guava is 6 grams with no modifier.",
"honeydew": "the exchange for honeydew is 10.3 grams with no modifier.",
"kiwi": "the exchange for kiwi is 6.4 grams with no modifier.",
"lemon": "the exchange for lemon is 9 grams with no modifier.",
"lime": "the exchange for lime is 9 grams with no modifier.",
"mandarin orange": "the exchange for mandarin orange is 6 grams with no modifier.",
"dried mango": "the exchange for dried mango is 1 grams with no modifier.",
"fresh mango": "the exchange for fresh mango is 5.7 grams with no modifier.",
"nectarine": "the exchange for nectarine is 8.6 grams with no modifier.",
"orange": "the exchange for orange is 7.9 grams with no modifier.",
"papaya": "the exchange for papaya is 9.6 grams with no modifier.",
"canned peach": "the exchange for canned peach is 6.7 grams with no modifier.",
"dried peach": "the exchange for dried peach is 1.5 grams with no modifier.",
"peach": "the exchange for peach is 9.5 grams with no modifier.",
"fresh peach": "the exchange for fresh peach is  grams with no modifier.",
"canned pear": "the exchange for canned pear is 6.5 grams with no modifier.",
"pear": "the exchange for pear is 6.3 grams with no modifier.",
"fresh pear": "the exchange for fresh pear is  grams with no modifier.",
"japanese persimmon": "the exchange for japanese persimmon is 5.2 grams with no modifier.",
"persimmon": "the exchange for persimmon is 2.9 grams with no modifier.",
"canned pineapple": "the exchange for canned pineapple is 7.2 grams with no modifier.",
"pineapple": "the exchange for pineapple is 7.6 grams with no modifier.",
"fresh pineapple": "the exchange for fresh pineapple is  grams with no modifier.",
"canned plum": "the exchange for canned plum is 6 grams with no modifier.",
"plum": "the exchange for plum is 8.2 grams with no modifier.",
"fresh plum": "the exchange for fresh plum is  grams with no modifier.",
"prune": "the exchange for prune is 1.1 grams with no modifier.",
"raisin": "the exchange for raisin is 1.2 grams with no modifier.",
"red raspberry": "the exchange for red raspberry is 7.6 grams with no modifier.",
"rhubarb": "the exchange for rhubarb is 18.4 grams with no modifier.",
"starfruit": "the exchange for starfruit is 12.9 grams with no modifier.",
"strawberry": "the exchange for strawberry is 12 grams with no modifier.",
"fresh strawberry": "the exchange for fresh strawberry is  grams with no modifier.",
"frozen strawberry": "the exchange for frozen strawberry is 10.5 grams with no modifier.",
"tangerine": "the exchange for tangerine is 7 grams with no modifier.",
"watermelon": "the exchange for watermelon is 12.2 grams with no modifier.",
"almond breeze chocolate": "the exchange for almond breeze chocolate is 47.4 grams with no modifier.",
"chocolate almond breeze": "the exchange for chocolate almond breeze is  grams with no modifier.",
"almond breeze": "the exchange for almond breeze is 79 grams with with a -0.5 gram modifier.",
"vanilla almond breeze": "the exchange for vanilla almond breeze is  grams with no modifier.",
"almond breeze vanilla": "the exchange for almond breeze vanilla is  grams with no modifier.",
"apple juice": "the exchange for apple juice is 8.5 grams with no modifier.",
"apricot nectar juice": "the exchange for apricot nectar juice is 6.8 grams with no modifier.",
"carrot juice": "the exchange for carrot juice is 9.8 grams with no modifier.",
"cranberry cocktail": "the exchange for cranberry cocktail is 6.9 grams with no modifier.",
"gatorade": "the exchange for gatorade is 16 grams with no modifier.",
"gatorade g 2": "the exchange for gatorade g 2 is 45 grams with no modifier.",
"grape juice": "the exchange for grape juice is 6.5 grams with no modifier.",
"grapefruit juice": "the exchange for grapefruit juice is 10.3 grams with no modifier.",
"fresh grapefruit juice": "the exchange for fresh grapefruit juice is  grams with no modifier.",
"grapefruit juice concentrate": "the exchange for grapefruit juice concentrate is 9.7 grams with no modifier.",
"unsweetened grapefruit juice": "the exchange for unsweetened grapefruit juice is 10.5 grams with no modifier.",
"lemon juice": "the exchange for lemon juice is 11.1 grams with no modifier.",
"fresh lemon juice": "the exchange for fresh lemon juice is  grams with no modifier.",
"frozen lemon juice": "the exchange for frozen lemon juice is 14.3 grams with no modifier.",
"orange juice": "the exchange for orange juice is 9 grams with no modifier.",
"papaya nectar juice": "the exchange for papaya nectar juice is 6.8 grams with no modifier.",
"papaya juice": "the exchange for papaya juice is  grams with no modifier.",
"pear nectar juice": "the exchange for pear nectar juice is 6.3 grams with no modifier.",
"pear juice": "the exchange for pear juice is  grams with no modifier.",
"pedialyte": "the exchange for pedialyte is 40 grams with no modifier.",
"pineapple juice": "the exchange for pineapple juice is 7.3 grams with no modifier.",
"prine juice": "the exchange for prine juice is 5.5 grams with no modifier.",
"chocolate soymilk": "the exchange for chocolate soymilk is 8.5 grams with no modifier.",
"chocolate silk soymilk": "the exchange for chocolate silk soymilk is  grams with no modifier.",
"plain soymilk": "the exchange for plain soymilk is 15.8 grams with no modifier.",
"plain silk soymilk": "the exchange for plain silk soymilk is  grams with no modifier.",
"unsweetened soymilk": "the exchange for unsweetened soymilk is 0 grams with no modifier.",
"unsweetened silk soymilk": "the exchange for unsweetened silk soymilk is  grams with no modifier.",
"vanilla soymilk": "the exchange for vanilla soymilk is 14.8 grams with no modifier.",
"vanilla silk soymilk": "the exchange for vanilla silk soymilk is  grams with no modifier.",
"tomato juice": "the exchange for tomato juice is 20 grams with no modifier.",
"v 8 juice": "the exchange for v 8 juice is 22 grams with no modifier.",
"almond butter": "the exchange for almond butter is 2.8 grams with with a -1.5 gram modifier.",
"cashew butter": "the exchange for cashew butter is 2.2 grams with with a -1 gram modifier.",
"cashew": "the exchange for cashew is 2.1 grams with with a -0.5 gram modifier.",
"roasted cashew": "the exchange for roasted cashew is  grams with no modifier.",
"coconut flour": "the exchange for coconut flour is 1.2 grams with with a -1.5 gram modifier.",
"unsweetened coconut": "the exchange for unsweetened coconut is 3.3 grams with with a -1.5 gram modifier.",
"raw coconut": "the exchange for raw coconut is 5.4 grams with with a -1.5 gram modifier.",
"toasted coconut": "the exchange for toasted coconut is 2 grams with with a -0.5 gram modifier.",
"pistachio": "the exchange for pistachio is 2 grams with with a -0.5 gram modifier.",
"sesame seed": "the exchange for sesame seed is 2.3 grams with with a -1 gram modifier.",
"flour": "the exchange for flour is 1.1 grams with no modifier.",
"all purpose flour": "the exchange for all purpose flour is  grams with no modifier.",
"white flour": "the exchange for white flour is  grams with no modifier.",
"corn starch": "the exchange for corn starch is 1.1 grams with no modifier.",
"cornstarch": "the exchange for cornstarch is  grams with no modifier.",
"cooked brown rice": "the exchange for cooked brown rice is 4 grams with no modifier.",
"dry brown rice": "the exchange for dry brown rice is 1.1 grams with no modifier.",
"brown rice": "the exchange for brown rice is  grams with no modifier.",
"egg noodle": "the exchange for egg noodle is 3.4 grams with no modifier.",
"cooked pasta": "the exchange for cooked pasta is 3 grams with no modifier.",
"dry pasta": "the exchange for dry pasta is 1.1 grams with no modifier.",
"cooked ramen": "the exchange for cooked ramen is 10 grams with no modifier.",
"cooked ramen noodle": "the exchange for cooked ramen noodle is  grams with no modifier.",
"dry ramen": "the exchange for dry ramen is 1.3 grams with no modifier.",
"dry ramen noodle": "the exchange for dry ramen noodle is  grams with no modifier.",
"tofu noodle": "the exchange for tofu noodle is 28.3 grams with no modifier.",
"shiritake noodle": "the exchange for shiritake noodle is  grams with no modifier.",
"tofu shiritake noodle": "the exchange for tofu shiritake noodle is  grams with no modifier.",
"cooked white rice": "the exchange for cooked white rice is 3.2 grams with no modifier.",
"dry white rice": "the exchange for dry white rice is 1.1 grams with no modifier.",
"a 1 steak sauce": "the exchange for a 1 steak sauce is 5.7 grams with no modifier.",
"barbeque sauce": "the exchange for barbeque sauce is 6.9 grams with no modifier.",
"frank's red hot": "the exchange for frank's red hot is 44.2 grams with no modifier.",
"frank's red hot sauce": "the exchange for frank's red hot sauce is  grams with no modifier.",
"heinz 57 sauce": "the exchange for heinz 57 sauce is 16 grams with no modifier.",
"horseradish": "the exchange for horseradish is 8 grams with no modifier.",
"ketchup": "the exchange for ketchup is 3.6 grams with no modifier.",
"heinz 57 ketchup": "the exchange for heinz 57 ketchup is 4.3 grams with no modifier.",
"heinze 57 reduced sugar ketchup": "the exchange for heinze 57 reduced sugar ketchup is 16 grams with no modifier.",
"marinara sauce": "the exchange for marinara sauce is 7.5 grams with no modifier.",
"dijon mustard": "the exchange for dijon mustard is 6.5 grams with no modifier.",
"yellow mustard": "the exchange for yellow mustard is 8.5 grams with no modifier.",
"salsa": "the exchange for salsa is 12.8 grams with no modifier.",
"soy sauce": "the exchange for soy sauce is 6.2 grams with no modifier.",
"sweet relish": "the exchange for sweet relish is 2.8 grams with no modifier.",
"": "the exchange for  is 7.5 grams with no modifier.",
"tomato sauce": "the exchange for tomato sauce is 11.5 grams with no modifier.",
"balsamic vinegar": "the exchange for balsamic vinegar is 6.2 grams with no modifier.",
"white vinegar": "the exchange for white vinegar is 20 grams with no modifier.",
"distilled white vinegar": "the exchange for distilled white vinegar is  grams with no modifier.",
"worcestershire sauce": "the exchange for worcestershire sauce is 5 grams with no modifier.",
"bagel chip": "the exchange for bagel chip is 1.2 grams with no modifier.",
"cheeto": "the exchange for cheeto is 1.7 grams with no modifier.",
"corn chip": "the exchange for corn chip is 1.6 grams with no modifier.",
"cool ranch dorito": "the exchange for cool ranch dorito is 1.4 grams with no modifier.",
"dorito": "the exchange for dorito is 1.4 grams with no modifier.",
"frito": "the exchange for frito is 1.6 grams with no modifier.",
"air popped popcorn": "the exchange for air popped popcorn is 1.1 grams with no modifier.",
"microwave popcorn": "the exchange for microwave popcorn is 1.5 grams with no modifier.",
"oil popped popcorn": "the exchange for oil popped popcorn is 1.5 grams with no modifier.",
"popcorn": "the exchange for popcorn is  grams with no modifier.",
"barbeque potato chip": "the exchange for barbeque potato chip is 1.6 grams with no modifier.",
"potato chip": "the exchange for potato chip is 1.6 grams with no modifier.",
"prezel": "the exchange for prezel is 1.1 grams with no modifier.",
"tortilla chip": "the exchange for tortilla chip is 1.5 grams with no modifier.",
"basil": "the exchange for basil is 14.5 grams with no modifier.",
"chive": "the exchange for chive is 13.1 grams with no modifier.",
"cilantro": "the exchange for cilantro is 17.2 grams with no modifier.",
"cumin": "the exchange for cumin is 1.6 grams with no modifier.",
"cumin seed": "the exchange for cumin seed is  grams with no modifier.",
"garlic": "the exchange for garlic is 2.5 grams with no modifier.",
"parsley": "the exchange for parsley is 10.7 grams with no modifier.",
"peppermint": "the exchange for peppermint is 5.4 grams with no modifier.",
"mint": "the exchange for mint is  grams with no modifier.",
"unsweetened baking chocolate": "the exchange for unsweetened baking chocolate is 2.3 grams with no modifier.",
"bakers unsweetened baking chocolate": "the exchange for bakers unsweetened baking chocolate is  grams with no modifier.",
"unsweetened cocoa": "the exchange for unsweetened cocoa is 1.3 grams with no modifier.",
"hershey's unsweetened cocoa": "the exchange for hershey's unsweetened cocoa is  grams with no modifier.",
"light chocolate syrup": "the exchange for light chocolate syrup is 3.2 grams with no modifier.",
"hershey's lite chocolate syrup": "the exchange for hershey's lite chocolate syrup is  grams with no modifier.",
"sugar free chocolate syrup": "the exchange for sugar free chocolate syrup is 5.3 grams with no modifier.",
"hershey's sugar free chocolate syrup": "the exchange for hershey's sugar free chocolate syrup is  grams with no modifier.",
"sugar free strawberry syrup": "the exchange for sugar free strawberry syrup is 7.8 grams with no modifier.",
"hershey's sugar free strawberry syrup": "the exchange for hershey's sugar free strawberry syrup is  grams with no modifier.",
"sugar free hot cocoa": "the exchange for sugar free hot cocoa is 1.2 grams with no modifier.",
"sugar free instant pudding": "the exchange for sugar free instant pudding is 1.2 grams with no modifier.",
"jello sugar free instant pudding": "the exchange for jello sugar free instant pudding is  grams with no modifier.",
"nestle unsweetened cocoa": "the exchange for nestle unsweetened cocoa is 1.3 grams with no modifier.",
"nestle unsweetened baking chocolate": "the exchange for nestle unsweetened baking chocolate is 2.8 grams with no modifier.",
"unsweetened pre-melted chocolate": "the exchange for unsweetened pre-melted chocolate is 2.8 grams with no modifier.",
"alfalfa sprout": "the exchange for alfalfa sprout is 13 grams with no modifier.",
"artichoke heart": "the exchange for artichoke heart is 7 grams with no modifier.",
"canned asparagus": "the exchange for canned asparagus is 23.5 grams with no modifier.",
"asparagus": "the exchange for asparagus is  grams with no modifier.",
"fresh asparagus": "the exchange for fresh asparagus is 16.4 grams with no modifier.",
"frozen asparagus": "the exchange for frozen asparagus is 20.5 grams with no modifier.",
"bamboo shoots": "the exchange for bamboo shoots is 20.3 grams with no modifier.",
"boiled black bean": "the exchange for boiled black bean is 3.1 grams with no modifier.",
"black bean": "the exchange for black bean is 4.4 grams with no modifier.",
"canned black bean": "the exchange for canned black bean is  grams with no modifier.",
"chickpea": "the exchange for chickpea is 3.6 grams with no modifier.",
"canned chickpea": "the exchange for canned chickpea is  grams with no modifier.",
"garbanzo bean": "the exchange for garbanzo bean is  grams with no modifier.",
"canned garbanzo bean": "the exchange for canned garbanzo bean is  grams with no modifier.",
"cooked garbanzo bean": "the exchange for cooked garbanzo bean is 2.7 grams with no modifier.",
"raw garbanzo bean": "the exchange for raw garbanzo bean is 1.2 grams with no modifier.",
"hummus": "the exchange for hummus is 4.5 grams with no modifier.",
"green bean": "the exchange for green bean is 10.2 grams with no modifier.",
"string bean": "the exchange for string bean is  grams with no modifier.",
"kidnet bean": "the exchange for kidnet bean is 3.2 grams with no modifier.",
"boiled lima bean": "the exchange for boiled lima bean is 3.3 grams with no modifier.",
"canned lima bean": "the exchange for canned lima bean is 5.8 grams with no modifier.",
"lima bean": "the exchange for lima bean is  grams with no modifier.",
"frozen lima bean": "the exchange for frozen lima bean is 3.8 grams with no modifier.",
"boiled navy bean": "the exchange for boiled navy bean is 2.9 grams with no modifier.",
"canned navy bean": "the exchange for canned navy bean is 3.6 grams with no modifier.",
"navy bean": "the exchange for navy bean is  grams with no modifier.",
"pinto bean": "the exchange for pinto bean is 2.8 grams with no modifier.",
"refried bean": "the exchange for refried bean is 4.7 grams with no modifier.",
"waxed bean": "the exchange for waxed bean is 12.6 grams with no modifier.",
"beet": "the exchange for beet is 8.6 grams with no modifier.",
"pickled beet": "the exchange for pickled beet is 6 grams with no modifier.",
"canned beet": "the exchange for canned beet is 12.4 grams with no modifier.",
"baked potato": "the exchange for baked potato is 2 grams with no modifier.",
"cooked broccoli": "the exchange for cooked broccoli is 12.4 grams with no modifier.",
"raw broccoli": "the exchange for raw broccoli is 10.5 grams with no modifier.",
"fresh broccoli": "the exchange for fresh broccoli is  grams with no modifier.",
"broccoli": "the exchange for broccoli is  grams with no modifier.",
"frozen broccoli": "the exchange for frozen broccoli is 11.8 grams with no modifier.",
"brussel sprout": "the exchange for brussel sprout is 8.9 grams with no modifier.",
"fresh brussel sprout": "the exchange for fresh brussel sprout is  grams with no modifier.",
"frozen brussel sprout": "the exchange for frozen brussel sprout is 8.4 grams with no modifier.",
"bak choi": "the exchange for bak choi is 27 grams with no modifier.",
"chinese cabbage": "the exchange for chinese cabbage is  grams with no modifier.",
"cooked cabbage": "the exchange for cooked cabbage is 18.2 grams with no modifier.",
"cooked green cabbage": "the exchange for cooked green cabbage is  grams with no modifier.",
"cabbage": "the exchange for cabbage is 14.2 grams with no modifier.",
"raw cabbage": "the exchange for raw cabbage is  grams with no modifier.",
"cooked red cabbage": "the exchange for cooked red cabbage is 17.6 grams with no modifier.",
"red cabbage": "the exchange for red cabbage is 11.4 grams with no modifier.",
"raw red cabbage": "the exchange for raw red cabbage is  grams with no modifier.",
"canned carrot": "the exchange for canned carrot is 16.3 grams with no modifier.",
"cooked carrot": "the exchange for cooked carrot is 11.1 grams with no modifier.",
"carrot": "the exchange for carrot is 9.5 grams with no modifier.",
"raw carrot": "the exchange for raw carrot is  grams with no modifier.",
"frozen carrot": "the exchange for frozen carrot is 12 grams with no modifier.",
"cooked cauliflower": "the exchange for cooked cauliflower is 16.7 grams with no modifier.",
"cauliflower": "the exchange for cauliflower is 13.8 grams with no modifier.",
"raw cauliflower": "the exchange for raw cauliflower is  grams with no modifier.",
"frozen cauliflower": "the exchange for frozen cauliflower is 18.8 grams with no modifier.",
"celery": "the exchange for celery is 27.3 grams with no modifier.",
"canned corn": "the exchange for canned corn is 4.7 grams with no modifier.",
"cooked corn": "the exchange for cooked corn is 3.5 grams with no modifier.",
"corn": "the exchange for corn is  grams with no modifier.",
"frozen corn": "the exchange for frozen corn is 4.5 grams with no modifier.",
"cucumber without peel": "the exchange for cucumber without peel is 36.4 grams with no modifier.",
"cucumber": "the exchange for cucumber is 23.3 grams with no modifier.",
"cucumber with peel": "the exchange for cucumber with peel is  grams with no modifier.",
"edamame": "the exchange for edamame is 4.4 grams with no modifier.",
"cooked eggplant": "the exchange for cooked eggplant is 10.4 grams with no modifier.",
"eggplant": "the exchange for eggplant is 15 grams with no modifier.",
"raw eggplant": "the exchange for raw eggplant is  grams with no modifier.",
"endive": "the exchange for endive is 21.7 grams with no modifier.",
"fennel": "the exchange for fennel is 11.7 grams with no modifier.",
"french fries": "the exchange for french fries is 3 grams with no modifier.",
"": "the exchange for  is 10.2 grams with no modifier.",
"collard green": "the exchange for collard green is 14.3 grams with no modifier.",
"collard": "the exchange for collard is  grams with no modifier.",
"dandelion green": "the exchange for dandelion green is 12 grams with no modifier.",
"escarole": "the exchange for escarole is 17 grams with no modifier.",
"kale": "the exchange for kale is 13.3 grams with no modifier.",
"kelp": "the exchange for kelp is 9 grams with no modifier.",
"mustard green": "the exchange for mustard green is 23 grams with no modifier.",
"heart of palm": "the exchange for heart of palm is 14 grams with no modifier.",
"hearts of palm": "the exchange for hearts of palm is  grams with no modifier.",
"hummus": "the exchange for hummus is 4.5 grams with no modifier.",
"jicama": "the exchange for jicama is 10.5 grams with no modifier.",
"boiled leek": "the exchange for boiled leek is 12 grams with no modifier.",
"leek": "the exchange for leek is 6.4 grams with no modifier.",
"lentil": "the exchange for lentil is 3.4 grams with no modifier.",
"boiled lentil": "the exchange for boiled lentil is  grams with no modifier.",
"bib lettuce": "the exchange for bib lettuce is 28 grams with no modifier.",
"butterhead lettuce": "the exchange for butterhead lettuce is  grams with no modifier.",
"iceberg lettuce": "the exchange for iceberg lettuce is 26 grams with no modifier.",
"romain lettuce": "the exchange for romain lettuce is 22.3 grams with no modifier.",
"canned mushroom": "the exchange for canned mushroom is 14.4 grams with no modifier.",
"mushroom": "the exchange for mushroom is 15 grams with no modifier.",
"fresh mushroom": "the exchange for fresh mushroom is  grams with no modifier.",
"okra": "the exchange for okra is 15.6 grams with no modifier.",
"fresk okra": "the exchange for fresk okra is  grams with no modifier.",
"boiled okra": "the exchange for boiled okra is  grams with no modifier.",
"frozen okra": "the exchange for frozen okra is 12.8 grams with no modifier.",
"jumbo black olive": "the exchange for jumbo black olive is 15.2 grams with with a -1 gram modifier.",
"black olive": "the exchange for black olive is 14.1 grams with with a -1.5 gram modifier.",
"canned black olive": "the exchange for canned black olive is  grams with no modifier.",
"green olive": "the exchange for green olive is 20.5 grams with with a -3 gram modifier.",
"cooked onion": "the exchange for cooked onion is 8.7 grams with no modifier.",
"onion": "the exchange for onion is 9.6 grams with no modifier.",
"raw onion": "the exchange for raw onion is  grams with no modifier.",
"boiled parsnip": "the exchange for boiled parsnip is 5.5 grams with no modifier.",
"parsnip": "the exchange for parsnip is 5.2 grams with no modifier.",
"raw parsnip": "the exchange for raw parsnip is  grams with no modifier.",
"canned pea": "the exchange for canned pea is 5.9 grams with no modifier.",
"canned green pea": "the exchange for canned green pea is  grams with no modifier.",
"boiled pea": "the exchange for boiled pea is 4.8 grams with no modifier.",
"boiled green pea": "the exchange for boiled green pea is  grams with no modifier.",
"pea": "the exchange for pea is 5 grams with no modifier.",
"raw pea": "the exchange for raw pea is  grams with no modifier.",
"fresh pea": "the exchange for fresh pea is  grams with no modifier.",
"green pea": "the exchange for green pea is  grams with no modifier.",
"raw green pea": "the exchange for raw green pea is  grams with no modifier.",
"fresh green pea": "the exchange for fresh green pea is  grams with no modifier.",
"frozen pea": "the exchange for frozen pea is 5.2 grams with no modifier.",
"frozen green pea": "the exchange for frozen green pea is  grams with no modifier.",
"snow pea": "the exchange for snow pea is 9.7 grams with no modifier.",
"fresh snow pea": "the exchange for fresh snow pea is  grams with no modifier.",
"boiled snow pea": "the exchange for boiled snow pea is  grams with no modifier.",
"frozen snow pea": "the exchange for frozen snow pea is 8 grams with no modifier.",
"sugar snap pea": "the exchange for sugar snap pea is 4 grams with no modifier.",
"green chili pepper": "the exchange for green chili pepper is 8.8 grams with no modifier.",
"red chili pepper": "the exchange for red chili pepper is 9.4 grams with no modifier.",
"canned jalapeño pepper": "the exchange for canned jalapeño pepper is 17.7 grams with no modifier.",
"jalapeño": "the exchange for jalapeño is 13.8 grams with no modifier.",
"raw jalapeño": "the exchange for raw jalapeño is  grams with no modifier.",
"jalapeño pepper": "the exchange for jalapeño pepper is  grams with no modifier.",
"green pepper": "the exchange for green pepper is 18.2 grams with no modifier.",
"bell pepper": "the exchange for bell pepper is  grams with no modifier.",
"green bell pepper": "the exchange for green bell pepper is  grams with no modifier.",
"red pepper": "the exchange for red pepper is 13.5 grams with no modifier.",
"red bell pepper": "the exchange for red bell pepper is  grams with no modifier.",
"yellow pepper": "the exchange for yellow pepper is 13.6 grams with no modifier.",
"yellow bell pepper": "the exchange for yellow bell pepper is  grams with no modifier.",
"bread and butter pickle": "the exchange for bread and butter pickle is 5.3 grams with no modifier.",
"dill pickle": "the exchange for dill pickle is 21 grams with no modifier.",
"sour pickle": "the exchange for sour pickle is 38.4 grams with no modifier.",
"sweet pickle": "the exchange for sweet pickle is 3.1 grams with no modifier.",
"baked potato": "the exchange for baked potato is 4.3 grams with no modifier.",
"french fry": "the exchange for french fry is 3 grams with no modifier.",
"pumpkin": "the exchange for pumpkin is 11 grams with no modifier.",
"canned pumpkin": "the exchange for canned pumpkin is  grams with no modifier.",
"radicchio": "the exchange for radicchio is 16.9 grams with no modifier.",
"radish": "the exchange for radish is 24.4 grams with no modifier.",
"boiled rhubarb": "the exchange for boiled rhubarb is 10 grams with no modifier.",
"rhubarb": "the exchange for rhubarb is 10.7 grams with no modifier.",
"raw rhubarb": "the exchange for raw rhubarb is  grams with no modifier.",
"sauerkraut": "the exchange for sauerkraut is 19.3 grams with no modifier.",
"scallion": "the exchange for scallion is 10.9 grams with no modifier.",
"canned spinach": "the exchange for canned spinach is 20 grams with no modifier.",
"spinach": "the exchange for spinach is 15.5 grams with no modifier.",
"fresh spinach": "the exchange for fresh spinach is  grams with no modifier.",
"frozen spinach": "the exchange for frozen spinach is 10.9 grams with no modifier.",
"sprout": "the exchange for sprout is 16.8 grams with no modifier.",
"baked acorn squash": "the exchange for baked acorn squash is 6.4 grams with no modifier.",
"boiled acorn squash": "the exchange for boiled acorn squash is 10.6 grams with no modifier.",
"acorn squash": "the exchange for acorn squash is 8.9 grams with no modifier.",
"fresh acorn squash": "the exchange for fresh acorn squash is  grams with no modifier.",
"butternut squash": "the exchange for butternut squash is 7.9 grams with no modifier.",
"raw butternut squash": "the exchange for raw butternut squash is  grams with no modifier.",
"fresh butternut squash": "the exchange for fresh butternut squash is  grams with no modifier.",
"frozen butternut squash": "the exchange for frozen butternut squash is 8.9 grams with no modifier.",
"canned crookneck squash": "the exchange for canned crookneck squash is 28 grams with no modifier.",
"crookneck squash": "the exchange for crookneck squash is 20 grams with no modifier.",
"fresh crookneck squash": "the exchange for fresh crookneck squash is  grams with no modifier.",
"frozen crookneck squash": "the exchange for frozen crookneck squash is 14.6 grams with no modifier.",
"spaghetti squash": "the exchange for spaghetti squash is 14.1 grams with no modifier.",
"zucchini": "the exchange for zucchini is 21.9 grams with no modifier.",
"fresh zucchini": "the exchange for fresh zucchini is  grams with no modifier.",
"frozen zucchini": "the exchange for frozen zucchini is 21 grams with no modifier.",
"string bean": "the exchange for string bean is 10.2 grams with no modifier.",
"sweet potato": "the exchange for sweet potato is 3.9 grams with no modifier.",
"canned sweet potato": "the exchange for canned sweet potato is 4 grams with no modifier.",
"frozen sweet potato": "the exchange for frozen sweet potato is 3.8 grams with no modifier.",
"boiled swiss chard": "the exchange for boiled swiss chard is 16.6 grams with no modifier.",
"swiss chard": "the exchange for swiss chard is 18 grams with no modifier.",
"raw swiss chard": "the exchange for raw swiss chard is  grams with no modifier.",
"tomatillo": "the exchange for tomatillo is 14.7 grams with no modifier.",
"tomato": "the exchange for tomato is 21 grams with no modifier.",
"fresh tomato": "the exchange for fresh tomato is  grams with no modifier.",
"tomato paste": "the exchange for tomato paste is 4.3 grams with no modifier.",
"tomato puree": "the exchange for tomato puree is 9.4 grams with no modifier.",
"stewed tomato": "the exchange for stewed tomato is 6.7 grams with no modifier.",
"turnip green": "the exchange for turnip green is 17.3 grams with no modifier.",
"turnip": "the exchange for turnip is 13.7 grams with no modifier.",
"fresh turnip": "the exchange for fresh turnip is  grams with no modifier.",
"frozen turnip": "the exchange for frozen turnip is 17 grams with no modifier.",
"water chestnut": "the exchange for water chestnut is 2.7 grams with no modifier.",
"watercress": "the exchange for watercress is 27.9 grams with no modifier.",
"yam": "the exchange for yam is 3.4 grams with no modifier.",
"zucchini": "the exchange for zucchini is 21.9 grams with no modifier.",
"frozen zucchini": "the exchange for frozen zucchini is 21 grams with no modifier.",
"canola oil": "the exchange for canola oil is 4 grams with no modifier.",
"coconut oil": "the exchange for coconut oil is 4 grams with no modifier.",
"cod liver oil": "the exchange for cod liver oil is 4 grams with no modifier.",
"corn oil": "the exchange for corn oil is 4 grams with no modifier.",
"flaxseed oil": "the exchange for flaxseed oil is 4 grams with no modifier.",
"m c t oil": "the exchange for m c t oil is 4 grams with no modifier.",
"olive oil": "the exchange for olive oil is 4 grams with no modifier.",
"sesame oil": "the exchange for sesame oil is 4 grams with no modifier.",
"sunflower oil": "the exchange for sunflower oil is 4 grams with no modifier.",
"vegetable oil": "the exchange for vegetable oil is 4 grams with no modifier.",
"walnut oil": "the exchange for walnut oil is 4 grams with no modifier.",
"butter": "the exchange for butter is 5 grams with no modifier.",
"margarine": "the exchange for margarine is 5 grams with no modifier.",
"smart balance": "the exchange for smart balance is 6.3 grams with no modifier.",
"smart balance spread": "the exchange for smart balance spread is  grams with no modifier.",
"earth balance": "the exchange for earth balance is 5.1 grams with no modifier.",
"earth balance spread": "the exchange for earth balance spread is  grams with no modifier.",
"mayo": "the exchange for mayo is 5 grams with no modifier.",
"mayonnaise": "the exchange for mayonnaise is  grams with no modifier.",
"veganaise": "the exchange for veganaise is 6 grams with no modifier.",
"benecol": "the exchange for benecol is 7 grams with no modifier.",
"microlipid": "the exchange for microlipid is 8 grams with no modifier.",
"bacon bit": "the exchange for bacon bit is 3.3 grams with no modifier.",
"bacon": "the exchange for bacon is 5 grams with with a -1 gram modifier.",
"turkey bacon": "the exchange for turkey bacon is 6.1 grams with with a -0.5 gram modifier.",
"louis rich turkey bacon": "the exchange for louis rich turkey bacon is 11.9 grams with with a -1.5 gram modifier.",
"lit'l smokies": "the exchange for lit'l smokies is 10 grams with with a -2.5 gram modifier.",
"smokies": "the exchange for smokies is  grams with no modifier.",
"pork roll": "the exchange for pork roll is 11.3 grams with with a -1.5 gram modifier.",
"taylor's pork roll": "the exchange for taylor's pork roll is 11 grams with with a -2 gram modifier.",
"turkey sausage": "the exchange for turkey sausage is 11.8 grams with with a -1 gram modifier.",
"fresh turkey sausage": "the exchange for fresh turkey sausage is 8.4 grams with no modifier.",
"smoked turkey sausage": "the exchange for smoked turkey sausage is 10.2 grams with no modifier.",
"vienna sausage": "the exchange for vienna sausage is 16 grams with with a -3.5 gram modifier.",
"pork sausage link": "the exchange for pork sausage link is 11.3 grams with with a -1.5 gram modifier.",
"pork sausage patty": "the exchange for pork sausage patty is 10.2 grams with with a -1 gram modifier.",
"sausage roll": "the exchange for sausage roll is 10.2 grams with with a -1.5 gram modifier.",
"habbersett sausage link": "the exchange for habbersett sausage link is 9.8 grams with with a -1.5 gram modifier.",
"habberset fully browned link": "the exchange for habberset fully browned link is 14.8 grams with with a -5 gram modifier.",
"habberset fully browned patty": "the exchange for habberset fully browned patty is 12.7 grams with with a -3.5 gram modifier.",
"jimmy dean fully cooked link": "the exchange for jimmy dean fully cooked link is 11.3 grams with with a -3 gram modifier.",
"jimmy dean fully cooked patty": "the exchange for jimmy dean fully cooked patty is 15.1 grams with with a -4 gram modifier.",
"jimmy deak sausage roll": "the exchange for jimmy deak sausage roll is 16 grams with with a -5 gram modifier.",
"scrappled": "the exchange for scrappled is 7.2 grams with no modifier.",
"american cheese": "the exchange for american cheese is 8.4 grams with with a -1.5 gram modifier.",
"blue cheese": "the exchange for blue cheese is 8.4 grams with with a -1.5 gram modifier.",
"brie": "the exchange for brie is 9.4 grams with with a -1.5 gram modifier.",
"brie cheese": "the exchange for brie cheese is  grams with no modifier.",
"camembert": "the exchange for camembert is 9.9 grams with with a -1.5 gram modifier.",
"camembert cheese": "the exchange for camembert cheese is  grams with no modifier.",
"cheddar": "the exchange for cheddar is 7.6 grams with with a -1.5 gram modifier.",
"cheddar cheese": "the exchange for cheddar cheese is  grams with no modifier.",
"cheez whiz": "the exchange for cheez whiz is 9.4 grams with with a -1 gram modifier.",
"colby cheese": "the exchange for colby cheese is 7.6 grams with with a -1 gram modifier.",
"cottage cheese": "the exchange for cottage cheese is 13.2 grams with with a 0.5 gram modifier.",
"neufchatel": "the exchange for neufchatel is 14 grams with with a -2 gram modifier.",
"cream cheese": "the exchange for cream cheese is 18.7 grams with with a -5.5 gram modifier.",
"cream cheese brick": "the exchange for cream cheese brick is  grams with no modifier.",
"tub cream cheese": "the exchange for tub cream cheese is 20.7 grams with with a -5 gram modifier.",
"whipped cream cheese": "the exchange for whipped cream cheese is 19.6 grams with with a -6 gram modifier.",
"whipped philadelphia cream cheese": "the exchange for whipped philadelphia cream cheese is 21 grams with with a -5 gram modifier.",
"edam cheese": "the exchange for edam cheese is 7.6 grams with with a -1 gram modifier.",
"edam cheese": "the exchange for edam cheese is  grams with no modifier.",
"feta cheese": "the exchange for feta cheese is 10.9 grams with with a -1 gram modifier.",
"feta": "the exchange for feta is  grams with no modifier.",
"gouda cheese": "the exchange for gouda cheese is 7.4 grams with with a -1 gram modifier.",
"gouda": "the exchange for gouda is  grams with no modifier.",
"gruyere": "the exchange for gruyere is 6.6 grams with with a -1 gram modifier.",
"gruyere cheese": "the exchange for gruyere cheese is  grams with no modifier.",
"havarti": "the exchange for havarti is 11.2 grams with with a -3 gram modifier.",
"havarti cheese": "the exchange for havarti cheese is  grams with no modifier.",
"jarlsberg": "the exchange for jarlsberg is 6.9 grams with with a -0.5 gram modifier.",
"jarlsberg cheese": "the exchange for jarlsberg cheese is  grams with no modifier.",
"monterey cheese": "the exchange for monterey cheese is 8 grams with with a -1.5 gram modifier.",
"part skim mozzerella cheese": "the exchange for part skim mozzerella cheese is 7.5 grams with with a -0.5 gram modifier.",
"part skim shredded mozzerella cheese": "the exchange for part skim shredded mozzerella cheese is 6.2 grams with no modifier.",
"whole milk mozzerella cheese": "the exchange for whole milk mozzerella cheese is 8.6 grams with with a -1 gram modifier.",
"whole milk shredded mozzerella cheese": "the exchange for whole milk shredded mozzerella cheese is 8.6 grams with with a -1 gram modifier.",
"muenster": "the exchange for muenster is 8.2 grams with with a -1.5 gram modifier.",
"neufchatel": "the exchange for neufchatel is 15.5 grams with with a -2.5 gram modifier.",
"parmesan": "the exchange for parmesan is 4.7 grams with no modifier.",
"parmesan cheese": "the exchange for parmesan cheese is  grams with no modifier.",
"provolone cheese": "the exchange for provolone cheese is 7.2 grams with with a -1 gram modifier.",
"provolone": "the exchange for provolone is  grams with no modifier.",
"queso fresco": "the exchange for queso fresco is 9.3 grams with with a -1.5 gram modifier.",
"part skim ricotta": "the exchange for part skim ricotta is 12 grams with no modifier.",
"whole milk ricotta": "the exchange for whole milk ricotta is 14 grams with with a -1 gram modifier.",
"ricotta cheese": "the exchange for ricotta cheese is  grams with no modifier.",
"romano cheese": "the exchange for romano cheese is 5.5 grams with with a -0.5 gram modifier.",
"romano": "the exchange for romano is  grams with no modifier.",
"string cheese": "the exchange for string cheese is 6.2 grams with with a 1 gram modifier.",
"swiss cheese": "the exchange for swiss cheese is 6.2 grams with with a -0.5 gram modifier.",
"velveeta": "the exchange for velveeta is 7 grams with with a -0.5 gram modifier.",
"whole milk": "the exchange for whole milk is 26 grams with no modifier.",
"evaporated milk": "the exchange for evaporated milk is 11.9 grams with no modifier.",
"breakstone sour cream": "the exchange for breakstone sour cream is 30 grams with with a -4 gram modifier.",
"daisy sour cream": "the exchange for daisy sour cream is  grams with no modifier.",
"horizon organic sour cream": "the exchange for horizon organic sour cream is  grams with no modifier.",
"shop rite sour cream": "the exchange for shop rite sour cream is  grams with no modifier.",
"sour cream": "the exchange for sour cream is 20 grams with with a -4 gram modifier.",
"light and fit yogurt": "the exchange for light and fit yogurt is 28.3 grams with with a 1 gram modifier.",
"carb and sugar control yogurt": "the exchange for carb and sugar control yogurt is  grams with no modifier.",
"danon whole milk yogurt": "the exchange for danon whole milk yogurt is 21.6 grams with with a 0.5 gram modifier.",
"danon yogurt": "the exchange for danon yogurt is  grams with no modifier.",
"fage total greek yogurt": "the exchange for fage total greek yogurt is 15.7 grams with with a 0.5 gram modifier.",
"greek yogurt": "the exchange for greek yogurt is  grams with no modifier.",
"horizon organic yogurt": "the exchange for horizon organic yogurt is 18.9 grams with with a 0.5 gram modifier.",
"horizon organic whole milk yogurt": "the exchange for horizon organic whole milk yogurt is  grams with no modifier.",
"stonyfield yogurt": "the exchange for stonyfield yogurt is 18.2 grams with with a 0.5 gram modifier.",
"stonyfield whole milk yogurt": "the exchange for stonyfield whole milk yogurt is  grams with no modifier.",
"all white": "the exchange for all white is 16 grams with with a 1 gram modifier.",
"better'n egg": "the exchange for better'n egg is 16 grams with with a 1 gram modifier.",
"egg beater": "the exchange for egg beater is 17.4 grams with with a 1 gram modifier.",
"egg beater white": "the exchange for egg beater white is 15.3 grams with with a 1 gram modifier.",
"egg beater with yolk": "the exchange for egg beater with yolk is 17.4 grams with with a 0.5 gram modifier.",
"fresh egg white": "the exchange for fresh egg white is 17.2 grams with with a 1 gram modifier.",
"egg white": "the exchange for egg white is  grams with no modifier.",
"fresh egg yolk": "the exchange for fresh egg yolk is 10.3 grams with with a -1.5 gram modifier.",
"egg yolk": "the exchange for egg yolk is  grams with no modifier.",
"egg": "the exchange for egg is 15 grams with with a -1 gram modifier.",
"whole egg": "the exchange for whole egg is  grams with no modifier.",
"beef bologna": "the exchange for beef bologna is 14 grams with with a -3 gram modifier.",
"oscar mayer bologna": "the exchange for oscar mayer bologna is 14.8 grams with with a -3 gram modifier.",
"beef and pork bologna": "the exchange for beef and pork bologna is 9.7 grams with with a -1.5 gram modifier.",
"oscar mayer chicken pork and beef bologna": "the exchange for oscar mayer chicken pork and beef bologna is 15 grams with with a -3 gram modifier.",
"lebanon bologna": "the exchange for lebanon bologna is 10.3 grams with no modifier.",
"turkey bologna": "the exchange for turkey bologna is 12.4 grams with with a -0.5 gram modifier.",
"bratwurst": "the exchange for bratwurst is 12.4 grams with with a -2.5 gram modifier.",
"louis rich chicken breast": "the exchange for louis rich chicken breast is 10 grams with with a 1 gram modifier.",
"oscar mayer chicken breast": "the exchange for oscar mayer chicken breast is 10 grams with with a 1 gram modifier.",
"light meat chicken roll": "the exchange for light meat chicken roll is 9.1 grams with with a 0.5 gram modifier.",
"boiled ham": "the exchange for boiled ham is 11.2 grams with with a 0.5 gram modifier.",
"extra lean ham": "the exchange for extra lean ham is 10 grams with with a 1 gram modifier.",
"honey ham": "the exchange for honey ham is 10.1 grams with with a 0.5 gram modifier.",
"ham": "the exchange for ham is 9.8 grams with no modifier.",
"smoked ham": "the exchange for smoked ham is 12 grams with with a 0.5 gram modifier.",
"turkey ham": "the exchange for turkey ham is 10.5 grams with with a 0.5 gram modifier.",
"beef hot dog": "the exchange for beef hot dog is 13.1 grams with with a -3 gram modifier.",
"hormel beef frank": "the exchange for hormel beef frank is 13.6 grams with with a -2.5 gram modifier.",
"oscar mayer beef frank": "the exchange for oscar mayer beef frank is 14.5 grams with with a -3.5 gram modifier.",
"chicken hot dog": "the exchange for chicken hot dog is 10.1 grams with with a -1 gram modifier.",
"empire chicken frank": "the exchange for empire chicken frank is 19 grams with with a -1 gram modifier.",
"kunzler chicken frank": "the exchange for kunzler chicken frank is 11.3 grams with with a -1 gram modifier.",
"empire turkey frank": "the exchange for empire turkey frank is 19 grams with with a -1.5 gram modifier.",
"kunzler turkey frank": "the exchange for kunzler turkey frank is 12.9 grams with with a -0.5 gram modifier.",
"oscar mayer turkey frank": "the exchange for oscar mayer turkey frank is 12.9 grams with with a -1 gram modifier.",
"knockwurst": "the exchange for knockwurst is 14 grams with with a -3 gram modifier.",
"liverwurst": "the exchange for liverwurst is 12.3 grams with with a -2.5 gram modifier.",
"beef pastrami": "the exchange for beef pastrami is 9.2 grams with with a 0.5 gram modifier.",
"pastrami": "the exchange for pastrami is  grams with no modifier.",
"turkey pastrami": "the exchange for turkey pastrami is 10 grams with with a 0.5 gram modifier.",
"hormel pepperoni": "the exchange for hormel pepperoni is 11.2 grams with with a -4 gram modifier.",
"turkey pepperoni": "the exchange for turkey pepperoni is 6.7 grams with no modifier.",
"pepperoni": "the exchange for pepperoni is 8.8 grams with with a -3 gram modifier.",
"roast beef": "the exchange for roast beef is 9.7 grams with with a 1 gram modifier.",
"beef salami": "the exchange for beef salami is 13.8 grams with with a -2 gram modifier.",
"genoa salami": "the exchange for genoa salami is 9.1 grams with with a -2 gram modifier.",
"hard salami": "the exchange for hard salami is 9.3 grams with with a -2 gram modifier.",
"turkey bologna": "the exchange for turkey bologna is 12.4 grams with with a -1 gram modifier.",
"turkey breast": "the exchange for turkey breast is 9.4 grams with with a 1 gram modifier.",
"smoked turkey": "the exchange for smoked turkey is 9.3 grams with with a 0.5 gram modifier.",
"smoked turkey breast": "the exchange for smoked turkey breast is 10.8 grams with with a 1 gram modifier.",
"beef brisket": "the exchange for beef brisket is 6.7 grams with no modifier.",
"blade roast": "the exchange for blade roast is 7.5 grams with with a -1 gram modifier.",
"pot roast": "the exchange for pot roast is 6.2 grams with with a 0.5 gram modifier.",
"corned beef": "the exchange for corned beef is 10.7 grams with with a -1 gram modifier.",
"chipped beef": "the exchange for chipped beef is 5.9 grams with with a 1 gram modifier.",
"flank steak": "the exchange for flank steak is 7.2 grams with with a 0.5 gram modifier.",
"lean ground beef": "the exchange for lean ground beef is 7 grams with no modifier.",
"ground beef": "the exchange for ground beef is 7 grams with with a 0.5 gram modifier.",
"new york strip": "the exchange for new york strip is 7.3 grams with no modifier.",
"porterhouse": "the exchange for porterhouse is 7.7 grams with with a -1.5 gram modifier.",
"porterhouse steak": "the exchange for porterhouse steak is  grams with no modifier.",
"prime rub": "the exchange for prime rub is 8.5 grams with with a -1 gram modifier.",
"ribeye": "the exchange for ribeye is 7 grams with with a 0.5 gram modifier.",
"bottom round": "the exchange for bottom round is 6.5 grams with no modifier.",
"shell steak": "the exchange for shell steak is 7 grams with with a 0.5 gram modifier.",
"skirt steak": "the exchange for skirt steak is 8.1 grams with no modifier.",
"steak-umm": "the exchange for steak-umm is 12.8 grams with with a -2.5 gram modifier.",
"beef tenderloin": "the exchange for beef tenderloin is 7 grams with no modifier.",
"top round": "the exchange for top round is 6.3 grams with with a 0.5 gram modifier.",
"top sirloin": "the exchange for top sirloin is 7 grams with no modifier.",
"canned chicken in broth": "the exchange for canned chicken in broth is 9.2 grams with with a 0.5 gram modifier.",
"canned chicken": "the exchange for canned chicken is 7.7 grams with with a 0.5 gram modifier.",
"dark meat chicken": "the exchange for dark meat chicken is 8 grams with no modifier.",
"ground chicken": "the exchange for ground chicken is 8.6 grams with no modifier.",
"ground light meat chicken": "the exchange for ground light meat chicken is 6.5 grams with with a 1 gram modifier.",
"light meat chicken": "the exchange for light meat chicken is 6.5 grams with with a 1 gram modifier.",
"cornish hen": "the exchange for cornish hen is 8.6 grams with with a 1 gram modifier.",
"duck": "the exchange for duck is 9 grams with with a -1 gram modifier.",
"canned ham": "the exchange for canned ham is 9.7 grams with no modifier.",
"roasted ham": "the exchange for roasted ham is 7.4 grams with no modifier.",
"spam": "the exchange for spam is 12.3 grams with with a -2.5 gram modifier.",
"keilbasa": "the exchange for keilbasa is 11.5 grams with with a -1 gram modifier.",
"lamb": "the exchange for lamb is 7.4 grams with no modifier.",
"pork": "the exchange for pork is 7 grams with no modifier.",
"pork rind": "the exchange for pork rind is 3.3 grams with no modifier.",
"beef sausage": "the exchange for beef sausage is 11.5 grams with with a -2 gram modifier.",
"italian sausage": "the exchange for italian sausage is 9 grams with with a -1 gram modifier.",
"sweet italian sausage": "the exchange for sweet italian sausage is 11 grams with no modifier.",
"pork and beef sausage": "the exchange for pork and beef sausage is 12.1 grams with with a -3.5 gram modifier.",
"smoked pork and beef sausage": "the exchange for smoked pork and beef sausage is 13.5 grams with with a -3 gram modifier.",
"pork sausage": "the exchange for pork sausage is 10.3 grams with with a -2 gram modifier.",
"smoked sausage": "the exchange for smoked sausage is 12.1 grams with with a -2 gram modifier.",
"dark meat turkey": "the exchange for dark meat turkey is 7 grams with with a 0.5 gram modifier.",
"ground turkey": "the exchange for ground turkey is 7.3 grams with no modifier.",
"ground light meat turkey": "the exchange for ground light meat turkey is 6.5 grams with with a 1 gram modifier.",
"light meat turkey": "the exchange for light meat turkey is 6.5 grams with with a 1 gram modifier.",
"ground veal": "the exchange for ground veal is 8.2 grams with with a 0.5 gram modifier.",
"veal": "the exchange for veal is 6.5 grams with no modifier.",
"venison": "the exchange for venison is 6.6 grams with with a 1 gram modifier.",
"new hope mills pancake mix": "the exchange for new hope mills pancake mix is 2.5 grams with with a 1 gram modifier.",
"almond": "the exchange for almond is 4.6 grams with with a -1 gram modifier.",
"oil roasted almond": "the exchange for oil roasted almond is 5.1 grams with with a -1.5 gram modifier.",
"dry roasted almond": "the exchange for dry roasted almond is 4.8 grams with with a -1.5 gram modifier.",
"brazil nut": "the exchange for brazil nut is 7.5 grams with with a -4 gram modifier.",
"flaxseed meal": "the exchange for flaxseed meal is 3.7 grams with no modifier.",
"": "the exchange for  is 3.7 grams with no modifier.",
"hazelnut": "the exchange for hazelnut is 6.2 grams with with a -2.5 gram modifier.",
"hazelnut flour": "the exchange for hazelnut flour is  grams with no modifier.",
"dry roasted hazelnut": "the exchange for dry roasted hazelnut is 6.1 grams with with a -2.5 gram modifier.",
"macadamia nut": "the exchange for macadamia nut is 9.4 grams with with a -6 gram modifier.",
"chunky peanut butter": "the exchange for chunky peanut butter is 4.4 grams with with a -1 gram modifier.",
"skippy natural creamy peanut butter": "the exchange for skippy natural creamy peanut butter is 4.9 grams with with a -1.5 gram modifier.",
"smucker natural creamy peanut butter": "the exchange for smucker natural creamy peanut butter is 4.6 grams with with a -1 gram modifier.",
"smooth peanut butter": "the exchange for smooth peanut butter is 4.5 grams with with a -1 gram modifier.",
"natural peanut butter": "the exchange for natural peanut butter is 4.6 grams with with a -1 gram modifier.",
"roasted peanut": "the exchange for roasted peanut is 4.4 grams with with a -1 gram modifier.",
"raw peanut": "the exchange for raw peanut is 4.8 grams with with a -1 gram modifier.",
"dry roasted pecan": "the exchange for dry roasted pecan is 8.7 grams with with a -5.5 gram modifier.",
"oil roasted pecan": "the exchange for oil roasted pecan is 9 grams with with a -6 gram modifier.",
"pine nut": "the exchange for pine nut is 7.5 grams with with a -4 gram modifier.",
"pumpkin seed": "the exchange for pumpkin seed is 4.3 grams with with a -1 gram modifier.",
"sesame seed": "the exchange for sesame seed is 6.2 grams with with a -3 gram modifier.",
"sunflower seed": "the exchange for sunflower seed is 4.9 grams with with a -1.5 gram modifier.",
"oil roasted sunflower seed": "the exchange for oil roasted sunflower seed is 4.7 grams with with a -1 gram modifier.",
"black walnut": "the exchange for black walnut is 5.9 grams with with a -2.5 gram modifier.",
"english walnnut": "the exchange for english walnnut is 6.9 grams with with a -3.5 gram modifier.",
"college inn beef broth": "the exchange for college inn beef broth is 113 grams with with a 0.5 gram modifier.",
"college in chicken broth": "the exchange for college in chicken broth is 452 grams with with a -1 gram modifier.",
"sugar free jello": "the exchange for sugar free jello is 3.2 grams with with a 1 gram modifier.",
"prepared sugar free jello": "the exchange for prepared sugar free jello is 242 grams with with a 1 gram modifier.",
"sugar free jello pack": "the exchange for sugar free jello pack is 8 grams with with a 1 gram modifier.",
"bass": "the exchange for bass is 8.3 grams with with a 1 gram modifier.",
"catfish": "the exchange for catfish is 10.7 grams with with a 0.5 gram modifier.",
"clams": "the exchange for clams is 6.6 grams with with a 1 gram modifier.",
"cod": "the exchange for cod is 8.7 grams with with a 1 gram modifier.",
"alaskan king crab": "the exchange for alaskan king crab is 10 grams with with a 1 gram modifier.",
"blue crab": "the exchange for blue crab is 10 grams with with a 1 gram modifier.",
"dungeness crab": "the exchange for dungeness crab is 8.5 grams with with a 1 gram modifier.",
"imitation crab": "the exchange for imitation crab is 9 grams with with a 1 gram modifier.",
"flounder": "the exchange for flounder is 8.3 grams with with a 1 gram modifier.",
"grouper": "the exchange for grouper is 8 grams with with a 1 gram modifier.",
"haddock": "the exchange for haddock is 8.3 grams with with a 1 gram modifier.",
"halibut": "the exchange for halibut is 7.5 grams with with a 1 gram modifier.",
"lobster": "the exchange for lobster is 9 grams with with a 1 gram modifier.",
"mussel": "the exchange for mussel is 6.4 grams with with a 1 gram modifier.",
"oyster": "the exchange for oyster is 9 grams with with a 0.5 gram modifier.",
"canned oyster": "the exchange for canned oyster is 18.2 grams with with a 0.5 gram modifier.",
"salmon": "the exchange for salmon is 8 grams with with a 0.5 gram modifier.",
"farmed atlantic salmon": "the exchange for farmed atlantic salmon is 9 grams with no modifier.",
"wild atlantic salmon": "the exchange for wild atlantic salmon is 7.9 grams with with a 0.5 gram modifier.",
"canned salmon": "the exchange for canned salmon is 10.1 grams with with a 0.5 gram modifier.",
"smoked salmon": "the exchange for smoked salmon is 10.9 grams with with a 0.5 gram modifier.",
"sardine": "the exchange for sardine is 8 grams with no modifier.",
"scallop": "the exchange for scallop is 8.6 grams with with a 1 gram modifier.",
"sea bass": "the exchange for sea bass is 8.5 grams with with a 1 gram modifier.",
"shad": "the exchange for shad is 9.2 grams with with a -0.5 gram modifier.",
"shrimp": "the exchange for shrimp is 9.6 grams with with a 1 gram modifier.",
"smelt": "the exchange for smelt is 9 grams with with a 1 gram modifier.",
"snapper": "the exchange for snapper is 7.6 grams with with a 1 gram modifier.",
"squid": "the exchange for squid is 9 grams with with a 0.5 gram modifier.",
"swordfish": "the exchange for swordfish is 8 grams with with a 0.5 gram modifier.",
"talapia": "the exchange for talapia is 8 grams with with a 1 gram modifier.",
"trout": "the exchange for trout is 7.5 grams with with a 0.5 gram modifier.",
"rainbow trout": "the exchange for rainbow trout is 8.7 grams with with a 0.5 gram modifier.",
"tuna in oil": "the exchange for tuna in oil is 7.5 grams with with a 0.5 gram modifier.",
"canned tuna in oil": "the exchange for canned tuna in oil is  grams with no modifier.",
"tuna in water": "the exchange for tuna in water is 8.5 grams with with a 1 gram modifier.",
"canned tuna in water": "the exchange for canned tuna in water is  grams with no modifier.",
"tuna steak": "the exchange for tuna steak is 6.5 grams with with a 1 gram modifier.",
"whitefish": "the exchange for whitefish is 8 grams with with a 0.5 gram modifier.",
"whitings fish": "the exchange for whitings fish is 8.5 grams with with a 1 gram modifier.",
"bob's red mill soy flour": "the exchange for bob's red mill soy flour is 3.1 grams with with a 0.5 gram modifier.",
"hodgson soy flour": "the exchange for hodgson soy flour is 2.5 grams with with a 1 gram modifier.",
"silk soymilk": "the exchange for silk soymilk is 43 grams with with a 0.5 gram modifier.",
"soymilk": "the exchange for soymilk is  grams with no modifier.",
"extra firm tofu": "the exchange for extra firm tofu is 15.8 grams with no modifier.",
"firm tofu": "the exchange for firm tofu is 17.6 grams with with a 0.5 gram modifier.",
"lite firm tofu": "the exchange for lite firm tofu is 22.6 grams with with a 0.5 gram modifier.",
"silken tofu": "the exchange for silken tofu is 30.3 grams with no modifier.",
"soft tofu": "the exchange for soft tofu is 22.6 grams with no modifier."
};
