/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at

        http://aws.amazon.com/apache2.0/

    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
"canola oil": "the exchange for canola oil is 4 grams with no modifier.",
"coconut oil": "the exchange for coconut oil is 4 grams with no modifier.",
"cod liver oil": "the exchange for cod liver oil is 4 grams with no modifier.",
"corn oil": "the exchange for corn oil is 4 grams with no modifier.",
"flaxseed oil": "the exchange for flaxseed oil is 4 grams with no modifier.",
"mct oil": "the exchange for mct oil is 4 grams with no modifier.",
"olive oil": "the exchange for olive oil is 4 grams with no modifier.",
"sesame oil": "the exchange for sesame oil is 4 grams with no modifier.",
"sunflower oil": "the exchange for sunflower oil is 4 grams with no modifier.",
"vegetable oil": "the exchange for vegetable oil is 4 grams with no modifier.",
"walnut oil": "the exchange for walnut oil is 4 grams with no modifier.",
"butter": "the exchange for butter is 5 grams with no modifier.",
"margarine": "the exchange for margarine is 5 grams with no modifier.",
"smart balance spread": "the exchange for smart balance spread is 6.3 grams with no modifier.",
"earth balance spread": "the exchange for earth balance spread is 5.1 grams with no modifier.",
"mayonnaise": "the exchange for mayonnaise is 5 grams with no modifier.",
"veganaise": "the exchange for veganaise is 6 grams with no modifier.",
"benecol": "the exchange for benecol is 7 grams with no modifier.",
"microlipid": "the exchange for microlipid is 8 grams with no modifier.",
"mayo": "the exchange for mayo is 5 grams with no modifier.",
"bacon bits": "the exchange for bacon bits is 3.3 grams with no modifier.",
"bacon": "the exchange for bacon is 5 grams with with a -1 gram modifier.",
"turkey bacon": "the exchange for turkey bacon is 6.1 grams with with a -0.5 gram modifier.",
"louis rich turkey bacon": "the exchange for louis rich turkey bacon is 11.9 grams with with a -1.5 gram modifier.",
"american cheese": "the exchange for american cheese is 8.4 grams with with a -1.5 gram modifier.",
"blue cheese": "the exchange for blue cheese is 8.4 grams with with a -1.5 gram modifier.",
"brie": "the exchange for brie is 9.4 grams with with a -1.5 gram modifier.",
"camembert cheese": "the exchange for camembert cheese is 9.9 grams with with a -1.5 gram modifier.",
"cheddar cheese": "the exchange for cheddar cheese is 7.6 grams with with a -1.5 gram modifier.",
"cheez whiz": "the exchange for cheez whiz is 9.4 grams with with a -1 gram modifier.",
"colby cheese": "the exchange for colby cheese is 7.6 grams with with a -1 gram modifier.",
"cottage cheese": "the exchange for cottage cheese is 13.2 grams with with a 0.5 gram modifier.",
"cream cheese": "the exchange for cream cheese is 14 grams with with a -2 gram modifier.",
"cream cheese brick": "the exchange for cream cheese brick is 18.7 grams with with a -5.5 gram modifier.",
"cream cheese tub": "the exchange for cream cheese tub is 20.7 grams with with a -5 gram modifier.",
"whipped cream cheese": "the exchange for whipped cream cheese is 19.6 grams with with a -6 gram modifier.",
"whipped philadelphia cream cheese": "the exchange for whipped philadelphia cream cheese is 21 grams with with a -5 gram modifier.",
"edam cheese": "the exchange for edam cheese is 7.6 grams with with a -1 gram modifier.",
"feta cheese": "the exchange for feta cheese is 10.9 grams with with a -1 gram modifier.",
"gouda cheese": "the exchange for gouda cheese is 7.4 grams with with a -1 gram modifier.",
"gruyere cheese": "the exchange for gruyere cheese is 6.6 grams with with a -1 gram modifier.",
"havarti cheese": "the exchange for havarti cheese is 11.2 grams with with a -3 gram modifier.",
"jarlsberg cheese": "the exchange for jarlsberg cheese is 6.9 grams with with a -0.5 gram modifier.",
"monterey cheese": "the exchange for monterey cheese is 8 grams with with a -1.5 gram modifier.",
"part skim block mozzarella cheese": "the exchange for part skim block mozzarella cheese is 7.5 grams with with a -0.5 gram modifier.",
"part skim shredded mozzarella cheese": "the exchange for part skim shredded mozzarella cheese is 6.2 grams with no modifier.",
"while milk block mozzarella cheese": "the exchange for while milk block mozzarella cheese is 8.6 grams with with a -1 gram modifier.",
"while milk shredded mozzarella cheese": "the exchange for while milk shredded mozzarella cheese is 8.6 grams with with a -1 gram modifier.",
"muenster cheese": "the exchange for muenster cheese is 8.2 grams with with a -1.5 gram modifier.",
"neufchatel cheese": "the exchange for neufchatel cheese is 15.5 grams with with a -2.5 gram modifier.",
"parmesan": "the exchange for parmesan is 4.7 grams with no modifier.",
"provolone": "the exchange for provolone is 7.2 grams with with a -1 gram modifier.",
"queso fresco": "the exchange for queso fresco is 9.3 grams with with a -1.5 gram modifier.",
"part skim ricotta": "the exchange for part skim ricotta is 12 grams with no modifier.",
"while milk ricotta": "the exchange for while milk ricotta is 14 grams with with a -1 gram modifier.",
"romano cheese": "the exchange for romano cheese is 5.5 grams with with a -0.5 gram modifier.",
"string cheese": "the exchange for string cheese is 6.2 grams with with a 1 gram modifier.",
"sweiss cheese": "the exchange for sweiss cheese is 6.2 grams with with a -0.5 gram modifier.",
"velveeta cheese block": "the exchange for velveeta cheese block is 7 grams with with a -0.5 gram modifier.",
"whole milk": "the exchange for whole milk is 26 grams with no modifier.",
"egg whites": "the exchange for egg whites is 16 grams with with a 1 gram modifier.",
"egg yolks": "the exchange for egg yolks is 10.3 grams with with a -1.5 gram modifier.",
"eggs": "the exchange for eggs is 15 grams with with a -1 gram modifier.",
"beef hot dogs": "the exchange for beef hot dogs is 13.1 grams with with a -3 gram modifier.",
"pepperoni": "the exchange for pepperoni is 11.2 grams with with a -4 gram modifier.",
"turkey pepperoni": "the exchange for turkey pepperoni is 6.7 grams with no modifier.",
"pork pepperoni": "the exchange for pork pepperoni is 8.8 grams with with a -3 gram modifier.",
"roast beef (lunch meat)": "the exchange for roast beef (lunch meat) is 9.7 grams with with a 1 gram modifier.",
"beef salami": "the exchange for beef salami is 13.8 grams with with a -2 gram modifier.",
"genoa salami": "the exchange for genoa salami is 9.1 grams with with a -2 gram modifier.",
"hard salami": "the exchange for hard salami is 9.3 grams with with a -2 gram modifier.",
"beef brisket": "the exchange for beef brisket is 6.7 grams with no modifier.",
"chuck blade roast": "the exchange for chuck blade roast is 7.5 grams with with a -1 gram modifier.",
"chuck pot roast": "the exchange for chuck pot roast is 6.2 grams with with a 0.5 gram modifier.",
"corned beef": "the exchange for corned beef is 10.7 grams with with a -1 gram modifier.",
"chipped beef": "the exchange for chipped beef is 5.9 grams with with a 1 gram modifier.",
"flank steak": "the exchange for flank steak is 7.2 grams with with a 0.5 gram modifier.",
"ground beef": "the exchange for ground beef is 7 grams with no modifier.",
"lean ground beef": "the exchange for lean ground beef is 7 grams with with a 0.5 gram modifier.",
"new york strip": "the exchange for new york strip is 7.3 grams with no modifier.",
"porterhouse": "the exchange for porterhouse is 7.7 grams with with a -1.5 gram modifier.",
"prime rib": "the exchange for prime rib is 8.5 grams with with a -1 gram modifier.",
"ribeye": "the exchange for ribeye is 7 grams with with a 0.5 gram modifier.",
"round bottom": "the exchange for round bottom is 6.5 grams with no modifier.",
"shell steak": "the exchange for shell steak is 7 grams with with a 0.5 gram modifier.",
"skirt steak": "the exchange for skirt steak is 8.1 grams with no modifier.",
"steak-umm": "the exchange for steak-umm is 12.8 grams with with a -2.5 gram modifier.",
"beef tenderloin": "the exchange for beef tenderloin is 7 grams with no modifier.",
"top round": "the exchange for top round is 6.3 grams with with a 0.5 gram modifier.",
"sirloin steak": "the exchange for sirloin steak is 7 grams with no modifier.",
"canned chicken in broth": "the exchange for canned chicken in broth is 9.2 grams with with a 0.5 gram modifier.",
"canned chicken no broth": "the exchange for canned chicken no broth is 7.7 grams with with a 0.5 gram modifier.",
"dark meat chicken": "the exchange for dark meat chicken is 8 grams with no modifier.",
"ground chicken": "the exchange for ground chicken is 8.6 grams with no modifier.",
"ground light meat chicken": "the exchange for ground light meat chicken is 6.5 grams with with a 1 gram modifier.",
"light meat chicken": "the exchange for light meat chicken is 6.5 grams with with a 1 gram modifier.",
"pork rinds": "the exchange for pork rinds is 3.3 grams with no modifier.",
"dark meat turkey": "the exchange for dark meat turkey is 7 grams with with a 0.5 gram modifier.",
"ground turkey": "the exchange for ground turkey is 7.3 grams with no modifier.",
"ground light meat turkey": "the exchange for ground light meat turkey is 6.5 grams with with a 1 gram modifier.",
"light meat turkey": "the exchange for light meat turkey is 6.5 grams with with a 1 gram modifier.",
"ground veal": "the exchange for ground veal is 8.2 grams with with a 0.5 gram modifier.",
"veal loin": "the exchange for veal loin is 6.5 grams with no modifier.",
"venison": "the exchange for venison is 6.6 grams with with a 1 gram modifier.",
"tuna in oil": "the exchange for tuna in oil is 7.5 grams with with a 0.5 gram modifier.",
"tuna in water": "the exchange for tuna in water is 8.5 grams with with a 1 gram modifier.",
"apple with skin": "the exchange for apple with skin is 7.1 grams with no modifier.",
"apple without skin": "the exchange for apple without skin is 7.7 grams with no modifier.",
"sweetened apple sauce": "the exchange for sweetened apple sauce is 5 grams with no modifier.",
"unsweetened apple sauce": "the exchange for unsweetened apple sauce is 8.7 grams with no modifier.",
"avocado": "the exchange for avacado is 9.5 grams with with a -1 gram modifier.",
"banana": "the exchange for banana is 4.2 grams with no modifier.",
"fresh blackberries": "the exchange for fresh blackberries is 9.1 grams with no modifier.",
"frozen blackberries": "the exchange for frozen blackberries is 6 grams with no modifier.",
"blueberries": "the exchange for blueberries is 6.5 grams with no modifier.",
"frozen blueberries": "the exchange for frozen blueberries is 8 grams with no modifier.",
"cantaloupe": "the exchange for cantaloupe is 11.1 grams with no modifier.",
"maraschino cherries": "the exchange for maraschino cherries is 2.3 grams with no modifier.",
"sour cherries": "the exchange for sour cherries is 7.6 grams with no modifier.",
"canned cherries": "the exchange for canned cherries is 8 grams with no modifier.",
"cherries": "the exchange for cherries is 5.9 grams with no modifier.",
"clementines": "the exchange for clementines is 7.8 grams with no modifier.",
"dried cranberries": "the exchange for dried cranberries is 1.2 grams with no modifier.",
"fresh cranberries": "the exchange for fresh cranberries is 7.9 grams with no modifier.",
"figs": "the exchange for figs is 1.5 grams with no modifier.",
"red grapefruit": "the exchange for red grapefruit is 8.8 grams with no modifier.",
"white grapefruit": "the exchange for white grapefruit is 11 grams with no modifier.",
"grapes": "the exchange for grapes is 5.5 grams with no modifier.",
"guavas": "the exchange for guavas is 6 grams with no modifier.",
"honeydew": "the exchange for honeydew is 10.3 grams with no modifier.",
"kiwi": "the exchange for kiwi is 6.4 grams with no modifier.",
"lemon": "the exchange for lemon is 9 grams with no modifier.",
"lime": "the exchange for lime is 9 grams with no modifier.",
"mandarin organge": "the exchange for mandarin organge is 6 grams with no modifier.",
"dried mango": "the exchange for dried mango is 1 grams with no modifier.",
"mango": "the exchange for mango is 5.7 grams with no modifier.",
"nectarine": "the exchange for nectarine is 8.6 grams with no modifier.",
"orange": "the exchange for orange is 7.9 grams with no modifier.",
"papayas": "the exchange for papayas is 9.6 grams with no modifier.",
"canned peaches": "the exchange for canned peaches is 6.7 grams with no modifier.",
"dried peaches": "the exchange for dried peaches is 1.5 grams with no modifier.",
"peaches": "the exchange for peaches is 9.5 grams with no modifier.",
"canned pears": "the exchange for canned pears is 6.5 grams with no modifier.",
"pear": "the exchange for pear is 6.3 grams with no modifier.",
"persimmons - japanese, raw": "the exchange for persimmons - japanese, raw is 5.2 grams with no modifier.",
"persimmons - native": "the exchange for persimmons - native is 2.9 grams with no modifier.",
"canned pineapple": "the exchange for canned pineapple is 7.2 grams with no modifier.",
"pineapple": "the exchange for pineapple is 7.6 grams with no modifier.",
"canned plums": "the exchange for canned plums is 6 grams with no modifier.",
"plums": "the exchange for plums is 8.2 grams with no modifier.",
"prunes": "the exchange for prunes is 1.1 grams with no modifier.",
"raisins": "the exchange for raisins is 1.2 grams with no modifier.",
"red raspberries": "the exchange for red raspberries is 7.6 grams with no modifier.",
"rhubarb": "the exchange for rhubarb is 18.4 grams with no modifier.",
"starfruit": "the exchange for starfruit is 12.9 grams with no modifier.",
"strawberries": "the exchange for strawberries is 12 grams with no modifier.",
"frozen strawberries": "the exchange for frozen strawberries is 10.5 grams with no modifier.",
"tangerine": "the exchange for tangerine is 7 grams with no modifier.",
"watermelon": "the exchange for watermelon is 12.2 grams with no modifier.",
"cucumber with peel": "the exchange for cucumber with peel is 23.3 grams with no modifier.",
"cucumber without peel": "the exchange for cucumber without peel is 36.4 grams with no modifier.",
"tomato": "the exchange for tomato is 21 grams with no modifier.",
"fresh tomato": "the exchange for fresh tomato is 21 grams with no modifier.",
"zucchini": "the exchange for zucchini is 21.9 grams with no modifier.",
"pickles:  dill": "the exchange for pickles:  dill is 21 grams with no modifier.",
"pickles:  sour": "the exchange for pickles:  sour is 38.4 grams with no modifier.",
"pickles:  sweet": "the exchange for pickles:  sweet is 3.1 grams with no modifier.",
"dill pickles": "the exchange for dill pickles is 21 grams with no modifier.",
"sour pickles": "the exchange for sour pickles is 38.4 grams with no modifier.",
"sweet pickles": "the exchange for sweet pickles is 3.1 grams with no modifier.",
"quest chips": "the exchange for quest chips is 2.5 grams with with a 1 gram modifier.",
"quest protein chips": "the exchange for quest protein chips is 2.5 grams with with a 1 gram modifier.",
"hemp milk": "the exchange for hemp milk is 160 grams with with a -4 gram modifier.",
"swanson natural goodness chicken broth": "the exchange for swanson natural goodness chicken broth is 160 grams with with a 1 gram modifier.",
/*common names*/
"dill pickles": "the exchange for dill pickles is 21 grams with no modifier.",
"cucumber": "the exchange for cucumber without peel is 36.4 grams with no modifier.",
"pork": "the exchange for pork loin is 7 grams with no modifier.",
"tuna": "the exchange for tuna in water is 8.5 grams with with a 1 gram modifier.",
"tuna fish": "the exchange for tuna in water is 8.5 grams with with a 1 gram modifier.",
"chicken": "the exchange for dark meat chicken is 8 grams with no modifier. the exchange for light meat chicken is 6.5 grams with with a 1 gram modifier.",

};
